---
- hosts: build_host
  gather_facts: no
  tasks:
    - name: create build directory
      file:
        path: ./dir-dockerfile
        state: directory
        owner: root
        group: root
        mode: '0755'
    - name: copy Dockerfile
      copy:
        src: ./Dockerfile
        dest: ./dir-dockerfile/Dockerfile
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: nginx:lastest
        build:
          path: ./dir-dockerfile
          source: build
        state: present
